
# Install only devDependencies due to the container being used as a
# “builder” that takes all the necessary tools to build the application
FROM node:16-alpine3.15

WORKDIR /app
RUN npm install react react-dom
RUN npm install @nestjs/common

ENV PATH /app/node_modules/.bin:$PATH

RUN mkdir -p /app/node_modules
RUN chown node:node /app/node_modules
COPY package*.json ./

RUN npm install

USER node

EXPOSE 3000
EXPOSE 35729
