FROM node:16-alpine

# Install necessary packages
RUN apk update \
    && apk add --no-cache yarn curl bash

WORKDIR /app
RUN mkdir -p /app/node_modules /app/dist
RUN chown node:node /app/node_modules /app/dist

COPY package.json package-lock.json ./

RUN npm install

USER node
